export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "@mantine/core/styles.css";

import styles from "./layout.module.css";
import GlobalHeader from "@/components/GlobalHeader/GlobalHeader";
import { NextAuthProvider } from "@/providers/NextAuth/NextAuthProvider";

import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_SITE_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    /** Your theme override here */
  });
  return (
    <html lang="en">
      <Head>
        <ColorSchemeScript />
      </Head>
      <NextAuthProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <MantineProvider theme={theme} defaultColorScheme="dark">
            <div className={styles.wrapper}>
              <GlobalHeader />
              <main>{children}</main>
            </div>
          </MantineProvider>
        </body>
      </NextAuthProvider>
    </html>
  );
}
